import { Megaphone, Newspaper, PartyPopper, CalendarDays, Building2, Rocket, Handshake, ShieldCheck, Gift } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { NewsletterBlock } from "@/lib/queries/newsletters";

export type NewsletterTemplateCategory = "Updates" | "Digest" | "Onboarding" | "Events" | "Company";

export interface NewsletterTemplate {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  /** Tailwind classes for the icon tile */
  accent: string;
  /** The template's signature color — used for the gallery thumbnail and matched to its banner/CTA blocks. */
  color: string;
  category: NewsletterTemplateCategory;
  subject: string;
  blocks: NewsletterBlock[];
}

export const NEWSLETTER_TEMPLATE_CATEGORIES: ("All" | NewsletterTemplateCategory)[] = [
  "All", "Updates", "Digest", "Onboarding", "Events", "Company",
];

const img = (id: string) => `https://images.unsplash.com/photo-${id}?w=1200&q=80&auto=format&fit=crop`;

export const newsletterTemplates: NewsletterTemplate[] = [
  {
    id: "product-update",
    name: "Product Update",
    description: "Announce new features and improvements to your subscribers.",
    icon: Megaphone,
    accent: "bg-blue-50 text-blue-600",
    color: "#2563eb",
    category: "Updates",
    subject: "What's new this month",
    blocks: [
      { type: "banner", text: "🚀 What's new this month", color: "#2563eb", textColor: "#ffffff" },
      { type: "image", url: img("1517694712202-14dd9538aa97"), alt: "Laptop with product dashboard" },
      { type: "paragraph", text: "Hi {{firstName}}, it's been a busy month on our end, and we wanted to walk you through everything we've shipped since our last update. Some of this came directly from feedback you sent us, so if you've ever asked \"can it also do X?\" — there's a good chance the answer below is yes. Grab a coffee, this one's worth reading in full." },
      { type: "divider" },
      { type: "heading", text: "New: [Feature name]" },
      { type: "image", url: img("1552664730-d307ca884978"), alt: "Product feature screenshot" },
      { type: "paragraph", text: "This is the headline feature of the release, and it addresses one of the most requested items in our feedback inbox. Previously, getting this done meant jumping between five different screens, copying data by hand, and hoping nothing got missed along the way. Now it's a single step, and it happens automatically in the background the moment you need it." },
      { type: "paragraph", text: "We built this after watching how our most active users were actually working around the old limitation — piecing together spreadsheets, sticky notes, and manual reminders. It's live for every plan starting today, there's nothing to install or configure, and your existing data will just slot right in the first time you open it." },
      { type: "cta", text: "See what's new", url: "https://example.com", color: "#2563eb" },
      { type: "divider" },
      { type: "heading", text: "Improved: [Existing feature]" },
      { type: "image", url: img("1518186285589-2f7649de83e0"), alt: "Team reviewing analytics on screen" },
      { type: "paragraph", text: "We also spent real time this month giving an existing part of the product some overdue attention. Loading times are noticeably faster, especially for teams with larger datasets, and we've cleaned up a handful of small inconsistencies in the interface that you may have quietly been working around without ever filing a ticket." },
      { type: "paragraph", text: "Under the hood, we rebuilt the syncing logic from scratch so changes now show up in real time across every device instead of requiring a manual refresh. If you've ever had two browser tabs open and seen them fall out of sync with each other, that specific annoyance should now be a thing of the past." },
      { type: "divider" },
      { type: "heading", text: "Coming soon" },
      { type: "paragraph", text: "Looking ahead, we're deep into building the next set of improvements, and a few of them are directly inspired by conversations we've had with customers over the past few weeks. We're not ready to share specifics just yet, but we're confident this next wave will be one of the more meaningful releases we've shipped in a while — we'll have more to say very soon." },
      { type: "cta", text: "Share your feedback", url: "https://example.com", color: "#2563eb" },
      { type: "divider" },
      { type: "paragraph", text: "As always, hit reply if you have questions, run into anything unexpected, or just want to tell us what you'd like to see next — a real person on our team reads every single message and we genuinely use this feedback to shape the roadmap." },
    ],
  },
  {
    id: "weekly-digest",
    name: "Weekly Digest",
    description: "A recurring roundup of highlights, links, and updates.",
    icon: Newspaper,
    accent: "bg-slate-100 text-slate-700",
    color: "#0f172a",
    category: "Digest",
    subject: "Your weekly digest",
    blocks: [
      {
        type: "section", color: "#0f172a", textColor: "#ffffff",
        eyebrow: "This week's highlights", heading: "Hey {{firstName}} 👋",
        text: "Another week has flown by, and there was a lot worth paying attention to. We read through everything so you don't have to, and pulled together the **three stories that mattered most**, plus a few smaller links worth a quick look when you have a spare minute.",
        url: img("1506905925346-21bda4d32df4"), alt: "Mountain landscape at sunrise", imagePosition: "top",
      },
      {
        type: "section", color: "#fef3c7",
        eyebrow: "Story 1", heading: "[Headline]",
        text: "Here's what happened, why it's significant, and what it means going forward. The short version: this changes the calculus for anyone who was on the fence, and it's worth understanding the details before you make your next move.",
        url: img("1497215728101-856f4ea42174"), alt: "Article header image", imagePosition: "left",
        ctaText: "Read more", ctaUrl: "https://example.com", ctaColor: "#d97706",
      },
      {
        type: "section", color: "#ede9fe",
        eyebrow: "Story 2", heading: "[Headline]",
        text: "A second story that's been generating a lot of conversation this week, with strong opinions on both sides. We've tried to lay out the strongest version of each argument so you can form your own view with the full picture in front of you.",
        url: img("1531973576160-7125cd663d86"), alt: "Second article header image", imagePosition: "left",
        ctaText: "Read more", ctaUrl: "https://example.com", ctaColor: "#7c3aed",
      },
      { type: "heading", text: "3. [Headline]" },
      { type: "paragraph", text: "A smaller but still noteworthy item that didn't get as much coverage elsewhere but is worth knowing about, especially if you're tracking this space closely. It may end up mattering more than it looks like right now — we'll keep following it and report back if anything changes." },
      { type: "divider" },
      { type: "heading", text: "Worth bookmarking" },
      { type: "paragraph", text: "• **[Link one](https://example.com)** — a longer explainer that's worth the extra ten minutes if you want the full context behind this week's biggest story." },
      { type: "paragraph", text: "• **[Link two](https://example.com)** — a useful tool or resource that a few readers recommended after last week's issue, and it's genuinely earned its spot on this list." },
      { type: "paragraph", text: "• **[Link three](https://example.com)** — a quick, lighter read to close things out, because not everything has to be serious all the time." },
      { type: "divider" },
      { type: "cta", text: "Read the full digest", url: "https://example.com", color: "#0f172a" },
      { type: "paragraph", text: "That's everything for this week. Reply and let us know what you thought, what we missed, or what you'd like to see covered next time — we read every response. See you next week." },
    ],
  },
  {
    id: "welcome-email",
    name: "Welcome Email",
    description: "Greet new subscribers and point them to their first win.",
    icon: PartyPopper,
    accent: "bg-emerald-50 text-emerald-600",
    color: "#059669",
    category: "Onboarding",
    subject: "Welcome! Here's where to start",
    blocks: [
      { type: "banner", text: "Welcome aboard, {{firstName}} 🎉", color: "#059669", textColor: "#ffffff" },
      { type: "image", url: img("1533174072545-7a4b6ad7a6c3"), alt: "Confetti celebration" },
      { type: "paragraph", text: "Thanks for subscribing — we're genuinely glad you're here. Whether you found us through a friend, a search, or pure curiosity, our goal is the same for everyone: get you to your first real win as quickly as possible, without a confusing setup process standing in the way. This email is a short map of exactly how to do that." },
      { type: "cta", text: "Get started", url: "https://example.com", color: "#059669" },
      { type: "divider" },
      { type: "heading", text: "Step 1 — [First action]" },
      { type: "image", url: img("1553877522-43269d4ea984"), alt: "Person getting started with a laptop" },
      { type: "paragraph", text: "This is the single most important thing to do first, and it only takes a couple of minutes. Once it's done, everything else becomes noticeably easier, so it's worth doing properly rather than skimming through it. If you get stuck at any point, the in-app guide will walk you through each screen step by step." },
      { type: "divider" },
      { type: "heading", text: "Step 2 — [Second action]" },
      { type: "image", url: img("1522071820081-009f0129c71c"), alt: "Person exploring a dashboard" },
      { type: "paragraph", text: "This is the natural next step once step one is out of the way, and it's usually the moment people start to see real value click into place. Take your time here — the more effort you put in now, the more useful everything downstream becomes, especially as you start bringing in your own data or team." },
      { type: "divider" },
      { type: "heading", text: "Step 3 — [Third action]" },
      { type: "paragraph", text: "This last step is optional, but it's a good one for anyone who wants to get more out of the product early on — think customizing your settings, inviting a teammate, or connecting one of your existing tools. None of this is required to get started, but most people end up doing it within their first week." },
      { type: "divider" },
      { type: "heading", text: "Need help?" },
      { type: "paragraph", text: "If anything above doesn't make sense, or you just want a second opinion on how to set things up for your specific use case, our help center has detailed guides for almost every scenario. And if you'd rather just talk to a human, reply to this email directly — a real person on our team reads every message and will get back to you personally, usually within a few hours." },
      { type: "cta", text: "Visit the help center", url: "https://example.com", color: "#059669" },
      { type: "paragraph", text: "Welcome again — we're genuinely excited to see what you end up building, and we'll be right here if you need anything along the way." },
    ],
  },
  {
    id: "event-announcement",
    name: "Event Announcement",
    description: "Invite subscribers to a webinar, launch, or in-person event.",
    icon: CalendarDays,
    accent: "bg-amber-50 text-amber-600",
    color: "#d97706",
    category: "Events",
    subject: "You're invited: [Event name]",
    blocks: [
      { type: "banner", text: "You're invited: [Event name]", color: "#d97706", textColor: "#ffffff" },
      { type: "image", url: img("1540575467063-178a50c2df87"), alt: "Calendar and event planning" },
      { type: "paragraph", text: "Hi {{firstName}}, we're excited to invite you to join us on [date] at [time] for [event description]. This is one we've been planning for a while, and we think it's going to be genuinely useful rather than just another webinar — we've kept the guest list and the agenda tight on purpose. Here's everything you need to know before you save your spot." },
      { type: "cta", text: "Save your spot", url: "https://example.com", color: "#d97706" },
      { type: "divider" },
      { type: "heading", text: "What to expect" },
      { type: "image", url: img("1556761175-5973dc0f32e7"), alt: "Audience at a conference" },
      { type: "paragraph", text: "We'll walk through the full agenda item by item, cover what's changed recently, and leave plenty of time at the end for open questions from the audience. This isn't going to be a straight lecture — expect live demos, real examples, and honest answers, including to the harder questions people usually only ask off the record." },
      { type: "divider" },
      { type: "heading", text: "Meet the speakers" },
      { type: "image", url: img("1531482615713-2afd69097998"), alt: "Speaker presenting on stage" },
      { type: "paragraph", text: "Our speakers bring a mix of hands-on experience and hard-won lessons from having done this the wrong way first. Rather than a polished pitch, expect a candid conversation about what actually worked, what didn't, and what they'd tell their past selves if they were starting over today." },
      { type: "divider" },
      { type: "heading", text: "Why it's worth your time" },
      { type: "paragraph", text: "By the end of the session, you should walk away with at least three things: a clearer picture of where things are heading, a couple of concrete tactics you can put into practice immediately, and direct access to ask our team anything that's specific to your own situation. We've designed it to be worth the hour, not just another calendar hold." },
      { type: "cta", text: "Save your spot", url: "https://example.com", color: "#d97706" },
      { type: "divider" },
      { type: "paragraph", text: "Can't make it live? Register anyway — we'll send a full recording straight to your inbox afterward, along with the slides and a summary of the questions that came up, so you won't miss a thing." },
    ],
  },
  {
    id: "company-news",
    name: "Company News",
    description: "Share milestones, team updates, or press mentions.",
    icon: Building2,
    accent: "bg-purple-50 text-purple-600",
    color: "#7c3aed",
    category: "Company",
    subject: "News from our team",
    blocks: [
      { type: "banner", text: "News from our team", color: "#7c3aed", textColor: "#ffffff" },
      { type: "image", url: img("1522202176988-66273c2fd55f"), alt: "Team meeting around a table" },
      { type: "paragraph", text: "Hi {{firstName}}, it's been a big quarter for us, and rather than let all of it trickle out separately, we wanted to bring you a proper update in one place — milestones we hit, new faces who've joined the team, and a look at what's ahead. Thanks for being part of this journey with us; a lot of what follows wouldn't have happened without customers like you." },
      { type: "divider" },
      { type: "heading", text: "[Milestone or news item]" },
      { type: "image", url: img("1543269865-cbf427effbad"), alt: "Team celebrating a milestone" },
      { type: "paragraph", text: "This milestone has been a long time coming, and it's the result of a lot of quiet, unglamorous work behind the scenes over the past several months. We wanted to take a moment to recognize the people who made it happen and explain why it matters — not just as a number to celebrate, but as a real signal of where things are heading for everyone who relies on us." },
      { type: "divider" },
      { type: "heading", text: "New faces on the team" },
      { type: "image", url: img("1454165804606-c3d57bc86b40"), alt: "New team members" },
      { type: "paragraph", text: "We've grown the team over the past few months, and we wanted to properly introduce the newest additions. Each of them brings a different background and a different set of strengths, and you'll likely interact with at least a few of them directly if you ever reach out to us for support, feedback, or a feature request." },
      { type: "divider" },
      { type: "heading", text: "In the press" },
      { type: "paragraph", text: "We've also picked up a bit of outside attention recently, including a couple of interviews and a feature that dug into how we think about building this product. If you're curious about the story behind the scenes, or just want more context on where we're headed next, these are worth a read." },
      { type: "cta", text: "Read the coverage", url: "https://example.com", color: "#7c3aed" },
      { type: "divider" },
      { type: "paragraph", text: "Thanks again for being part of our journey — genuinely, none of this happens without the people who use and support what we're building every day. More updates soon." },
    ],
  },
  {
    id: "product-launch",
    name: "Product Launch",
    description: "Build hype and drive signups for a brand-new launch.",
    icon: Rocket,
    accent: "bg-rose-50 text-rose-600",
    color: "#e11d48",
    category: "Updates",
    subject: "It's here: [Product name]",
    blocks: [
      { type: "banner", text: "🔥 It's finally here: [Product name]", color: "#e11d48", textColor: "#ffffff" },
      { type: "image", url: img("1449824913935-59a10b8d2000"), alt: "City skyline at dusk" },
      { type: "paragraph", text: "Hi {{firstName}}, after months of building, testing, throwing things away, and building them again, we're thrilled to finally launch [product name]. This wasn't built in a vacuum — it came directly out of conversations with customers who kept running into the same wall, and we think what we've ended up with genuinely solves that problem rather than just papering over it." },
      { type: "cta", text: "Try it now", url: "https://example.com", color: "#e11d48" },
      { type: "divider" },
      { type: "heading", text: "Why you'll love it" },
      { type: "image", url: img("1553028826-f4804a6dba3b"), alt: "Product interface close-up" },
      { type: "paragraph", text: "The first reason is simple: it removes an entire category of manual work that used to eat up hours every week, and it does it without asking you to change how you already operate. This isn't a bolt-on feature — it's built into the core experience, so it feels native from the very first time you use it." },
      { type: "paragraph", text: "The second reason is just as important — the results compound over time. The more you use it, the smarter it gets about your specific workflow, and early testers have told us they noticed a real difference within the first week alone, not months down the line." },
      { type: "divider" },
      { type: "heading", text: "How it works" },
      { type: "image", url: img("1600880292203-757bb62b4baf"), alt: "Person using the new product" },
      { type: "paragraph", text: "You don't need to change any of your existing setup to use this — it plugs directly into what you're already doing. From the moment you turn it on, it starts picking up context automatically, and within a few minutes you should already start noticing suggestions and shortcuts that feel like they were built specifically for how you work." },
      { type: "divider" },
      { type: "heading", text: "Launch pricing" },
      { type: "paragraph", text: "It's available starting today at [price], and as a thank-you to everyone who's been with us early, we're offering a limited discount for the first [number] people who sign up this week. There's no long-term contract, no hidden setup fee, and you can cancel any time if it's not the right fit — though we're confident it will be." },
      { type: "cta", text: "Claim early access", url: "https://example.com", color: "#e11d48" },
      { type: "divider" },
      { type: "paragraph", text: "This is very much a first version, and early feedback is going to shape what we build next more than anything else. If something feels off, or if there's a use case we haven't thought of, hit reply — we're reading and responding to every message this week." },
    ],
  },
  {
    id: "customer-story",
    name: "Customer Story",
    description: "Showcase a case study or customer win to build trust.",
    icon: Handshake,
    accent: "bg-teal-50 text-teal-600",
    color: "#0d9488",
    category: "Company",
    subject: "How [Customer] achieved [result]",
    blocks: [
      { type: "banner", text: "Customer spotlight: [Customer name]", color: "#0d9488", textColor: "#ffffff" },
      { type: "image", url: img("1521791136064-7986c2920216"), alt: "Handshake between two people" },
      { type: "paragraph", text: "Hi {{firstName}}, one of the best parts of this job is watching a customer take something we built and turn it into a real result for their own business. This week we sat down with [customer name] to talk through exactly how they used our product to achieve [result] — in their own words, warts and all, not just the highlight reel." },
      { type: "divider" },
      { type: "heading", text: "The challenge" },
      { type: "image", url: img("1460925895917-afdab827c52f"), alt: "Team discussing a challenge" },
      { type: "paragraph", text: "Before making the switch, their team was stitching together a handful of disconnected tools, and small errors kept slipping through the cracks at exactly the wrong moments. It wasn't a dramatic crisis — just a slow, steady drag on time and confidence that eventually became impossible to ignore, especially as the team started to grow." },
      { type: "divider" },
      { type: "heading", text: "The solution" },
      { type: "image", url: img("1504384308090-c894fdcc538d"), alt: "Team implementing a new solution" },
      { type: "paragraph", text: "The rollout itself took less time than they expected — most of the team was comfortable within the first week, and there was no need for a lengthy training program or a dedicated implementation specialist. They started with a single small workflow, proved it out, and then expanded from there once the team could see it working with their own eyes." },
      { type: "divider" },
      {
        type: "section", color: "#ccfbf1",
        eyebrow: "The result", heading: "[Customer name] in their own words",
        text: "A few months in, the numbers speak for themselves — **fewer errors, faster turnaround**, and a team that finally trusts the process enough to stop double-checking everything by hand. What started as a workaround for one recurring headache has since become the way the entire team operates day to day.",
        url: img("1486406146926-c627a92ad1ab"), alt: "Team celebrating results", imagePosition: "left",
        quote: "\"Switching over paid for itself within the first month, and it kept paying off every month after that. I genuinely wish we'd done this a year earlier.\" — [Name, Title, Company]",
        ctaText: "Read the full story", ctaUrl: "https://example.com", ctaColor: "#0d9488",
      },
    ],
  },
  {
    id: "security-update",
    name: "Security & Trust Update",
    description: "Reassure customers with a clear update on security, privacy, or compliance.",
    icon: ShieldCheck,
    accent: "bg-slate-100 text-slate-700",
    color: "#1e40af",
    category: "Company",
    subject: "An update on how we protect your data",
    blocks: [
      { type: "banner", text: "🔒 An update on how we protect your data", color: "#1e40af", textColor: "#ffffff" },
      { type: "paragraph", text: "Hi {{firstName}}, trust is something we take seriously, and we wanted to give you a clear, direct update on the security and privacy work we've done recently — not buried in a policy page, but explained plainly, in one place." },
      { type: "divider" },
      {
        type: "section", color: "#dbeafe",
        eyebrow: "What changed", heading: "[Security improvement or certification]",
        text: "We've made a concrete improvement to how your data is protected — whether that's a new certification, an infrastructure upgrade, or a policy change. Here's exactly what changed and why it matters for you, in plain language rather than legal jargon.",
        url: img("1591696205602-2f950c417cb9"), alt: "Security and data protection", imagePosition: "left",
      },
      { type: "divider" },
      {
        type: "section", color: "#ede9fe",
        eyebrow: "What you should know", heading: "Nothing you need to do",
        text: "This update doesn't require any action on your end — your account, your data, and your existing integrations all continue to work exactly as they do today. We'll always tell you directly, and well in advance, if anything ever does require a change from you.",
        url: img("1516321497487-e288fb19713f"), alt: "Team reviewing security practices", imagePosition: "right",
      },
      { type: "divider" },
      { type: "heading", text: "Questions?" },
      { type: "paragraph", text: "If you have questions about how we handle data, our full security and privacy documentation is always available, and our team is happy to walk through specifics for your organization on a call." },
      { type: "cta", text: "View our security practices", url: "https://example.com", color: "#1e40af" },
      { type: "divider" },
      { type: "paragraph", text: "Thanks for trusting us with your data — we don't take that lightly, and we'll keep being upfront with you as things evolve." },
    ],
  },
  {
    id: "referral-program",
    name: "Referral & Rewards",
    description: "Promote a referral program or limited-time reward to drive word-of-mouth.",
    icon: Gift,
    accent: "bg-pink-50 text-pink-600",
    color: "#db2777",
    category: "Updates",
    subject: "Give [reward], get [reward]",
    blocks: [
      { type: "banner", text: "🎁 Give [reward], get [reward]", color: "#db2777", textColor: "#ffffff" },
      { type: "paragraph", text: "Hi {{firstName}}, the best recommendations always come from people who actually use the product — so we built a way to say thank you when you send someone our way. Here's exactly how it works and what's in it for both of you." },
      { type: "divider" },
      {
        type: "section", color: "#fce7f3",
        eyebrow: "How it works", heading: "Three simple steps",
        text: "Share your unique referral link with a friend or colleague. When they sign up and get started, you both get rewarded — no minimum spend, no fine print, and no cap on how many times you can do this.",
        url: img("1556909114-f6e7ad7d3136"), alt: "People sharing on social media", imagePosition: "left",
        ctaText: "Get your referral link", ctaUrl: "https://example.com", ctaColor: "#db2777",
      },
      { type: "divider" },
      {
        type: "section", color: "#fef3c7",
        eyebrow: "What you'll get", heading: "[Reward details]",
        text: "For every successful referral, you'll receive [reward], and your friend gets [reward] too, applied automatically — no codes to remember or forms to fill out.",
        url: img("1546069901-ba9599a7e63c"), alt: "Celebrating a reward", imagePosition: "top",
      },
      { type: "divider" },
      { type: "paragraph", text: "\"I referred three people in my first month just because I genuinely wanted them to have it — the rewards were a nice bonus on top.\" — [Name, Customer]" },
      { type: "cta", text: "Start referring", url: "https://example.com", color: "#db2777" },
    ],
  },
];

export function getNewsletterTemplate(id: string | null | undefined): NewsletterTemplate | null {
  if (!id) return null;
  return newsletterTemplates.find((t) => t.id === id) || null;
}
