# syntax=docker/dockerfile:1

###############################################################################
# Base image shared by every stage
###############################################################################
FROM node:22-alpine AS base
WORKDIR /app
# Next.js on Alpine needs libc6-compat for some native deps (sharp, etc.)
RUN apk add --no-cache libc6-compat

###############################################################################
# 1. deps — install dependencies only (cached layer, invalidated only by
#    package.json / lockfile changes)
###############################################################################
FROM base AS deps
COPY package.json package-lock.json* .npmrc* ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci --no-audit --no-fund

###############################################################################
# 2. builder — build the Next.js app using the standalone output target
###############################################################################
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Accepted so the GKE workflow's --build-arg GITHUB_SHA/--build-arg
# GITHUB_REF don't trigger "build-arg not consumed" warnings. Not used by
# the build itself; wire into NEXT_PUBLIC_* below if you want the commit
# baked into the client bundle for display somewhere.
ARG GITHUB_SHA
ARG GITHUB_REF

# Public NEXT_PUBLIC_* values must be present at BUILD time because Next.js
# inlines them into the client bundle. Pass any you need with --build-arg
# and export them as ENV before `next build` runs. Example:
#   ARG NEXT_PUBLIC_SUPABASE_URL
#   ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

###############################################################################
# 3. runner — minimal production image, runs as a non-root user
###############################################################################
FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# `output: "standalone"` in next.config.js produces a self-contained
# server bundle plus a pruned node_modules — copy exactly that.
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by the standalone build output
CMD ["node", "server.js"]
